sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7-dev'
- 'pypy'
- 'pypy3'
branches:
  only:
  - master
install:
  - pip install pybuilder
  - pyb install_dependencies --verbose
script:
  - pyb --debug